experiment:
    name: "Debug lstm autoencoder perm50 with 0.05 dataset (0.05 dropout)"
    base_path: "/scratch/cl5503/cost_model_lstm_autoencoder"

data_generation:
    train_dataset_file: "/scratch/cl5503/data/afif/dataset_expr_batch550000-838143_debug.pkl"  # training / validation set
    valid_dataset_file: "/scratch/cl5503/data/afif/dataset_expr_batch550000-838143_debug.pkl"
    benchmark_dataset_file: "/data/kb4083/model_release/release_code/result_subsample.json"
    dataset_name:  "debug_data"
    batch_size: 512
    nb_processes: 1
    min_functions_per_tree_footprint: 2


training: 
    log_file: "logs.txt" # Just the name
    lr: 0.001
    max_epochs: 650
    training_gpu: "0" # cuda:0
    validation_gpu: "cpu"
    continue_training: False
    model_weights_path: "/data/kb4083/cost_model/weights/best_model_Baseline_old_patterns_ASPLOS_4675.pt"
    pretrained_weights_path: "/scratch/cl5503/cost_model_lstm_autoencoder/pre_train/saved_models/lstm_autoencoder_perm100_005drop.pt"
    use_fraction_data: 1.0 # used to test smaller dataset if set to < 1
    fine_tune_epoch: 120 # the epoch after which the pre-trained weights are unfreezed
    fine_tune_lr: 0.0002 # the learning rate of the pre-trained weights

testing:
    testing_model_weights_path: "/scratch/cl5503/cost_model_lstm_autoencoder/weights/best_model_lstm autoencoder perm50 with 0.5 dataset (0.05 dropout)_b166.pt" # Model weights to evaluate
    gpu: "cuda:0" # GPU to validate on

wandb:
    use_wandb: True
    project: "CGO25"
    
model: 
    input_size: 1573
    comp_embed_layer_sizes:
        - 600
        - 350
        - 200
        - 180
    drops:
        - 0.050
        - 0.050
        - 0.050
        - 0.050
        - 0.050

defaults:
  - override hydra/job_logging: disabled

# /data/kb4083/datasets/all_nr_data/dataset_expr_batch101-1227605_clean_train.pkl
# /scratch/cl5503/data/afif/dataset_expr_batch550000-838143_debug.pkl
# /scratch/cl5503/data/afif/new_dataset_expr_batch550000-838143_train.pkl
# /scratch/cl5503/data/afif/new_dataset_expr_batch550000-838143_val.pkl